### PR TITLE
add simple scripting with javascript

### PR DESCRIPTION
**Pull request by Nobodyno-boop**
Hello, like the discussion in #7
I have implemented a simple javascript systems.

VM used: [shadowrealm-api](https://www.npmjs.com/package/shadowrealm-api)

exemple of why:
We have a dashboard variable named "username" can be selected and we want to be used inside a query or not.

code js:
```js
function aggregate() {
    const _user = String("$username") === "all" ? null : String("$username");
    return [
        {
            "$match": {
                "createdAt": {
                    "$gt": {
                        "$date": {
                            "$numberLong": "$__from"
                        }
                    },
                    "$lt": {
                        "$date": {
                            "$numberLong": "$__to"
                        }
                    }
                },
                ...(_user ? {"username": _user} : {})
            }
        },
        {
            "$project": {
                "name": 1,
            }
        }
    ]
}
```
it will only be used for return an array of the aggregate for being used dynamicly.

### CODE REVIEW

**Comment by haohanyang** [comment]
Thank you. Can you keep the previous regex parsing and make this feature an option? For example adding a third queryLanguage option: JavascriptShadow? Think is for the compatibility of an old plugin

**Comment by Nobodyno-boop** [comment]
> Thank you. Can you keep the previous regex parsing and make this feature an option? For example adding a third queryLanguage option: JavascriptShadow? This is for the compatibility of an old plugin

Sure, i will do it

**Comment by Nobodyno-boop** [comment]
Hello @haohanyang i have update the PR for the compatibility.

- The checkbox for selection is now a Select of grafana ui (should not break the actual.)
- `parseJsQuery` for the compatibility have been named `parseJsQueryLegacy` to avoid confusion. feel free to rename it.
- i have added one more test unit for test the "javascript" 

I hope you have a great weekend!

**Comment by haohanyang** [comment]
Thanks. Looks good to me. Just need to fix CI

**Pull request merged**
